Repository puppetlabs/puppetlabs-resource, pull requests merged in 2019-12, with the labels that each got.

#73 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
  spec/acceptance/nodesets/centos-7-x64.yml
  spec/acceptance/nodesets/centos7-pooler.yml
  spec/acceptance/nodesets/debian-8-x64.yml
  spec/acceptance/nodesets/default.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
Labels: backwards-incompatible

#74 (maint) - v1.0.0 Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#75 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#76 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#77 (maint) - 1.1.0 Release Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#78 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#80 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
